extends Node

signal player_moved(new_position: Vector2i)
signal map_changed(map_id: String)
signal combat_started()
signal combat_ended()
signal combat_log(text: String)
signal player_turn_started()
signal dialogue_started(dialogue_id: String)
signal dialogue_ended(dialogue_id: String)
signal quest_started(quest_id: String)
signal quest_ready(quest_id: String)
signal quest_completed(quest_id: String)
signal inventory_changed()
signal equipment_changed()
signal quick_slots_changed()
signal xp_gained(amount: int)
signal player_leveled_up(new_level: int)
signal player_died()
signal player_stats_changed()
signal world_flag_changed(flag_name: String, value: bool)
signal enemy_died(enemy: Node)
signal turn_started(actor: Variant)
signal turn_ended(actor: Variant)
signal settings_changed()
signal notification_shown(n: Notification)
