extends Node

signal player_moved(new_position: Vector2i)
signal map_changed(map_id: String)
signal combat_started()
signal combat_ended()
signal combat_log(text: String)
signal player_turn_started()
signal dialogue_started(dialogue_id: String)
signal dialogue_ended(dialogue_id: String)
signal quest_started(quest_id: String)
signal quest_ready(quest_id: String)
signal quest_completed(quest_id: String)
signal inventory_changed()
signal equipment_changed()
signal quick_slots_changed()
signal xp_gained(amount: int)
signal player_leveled_up(new_level: int)
signal player_died()
signal player_stats_changed()
signal world_flag_changed(flag_name: String, value: bool)
signal enemy_died(enemy: Node)
signal turn_started(actor: Variant)
signal turn_ended(actor: Variant)
signal settings_changed()
signal notification_shown(n: Notification)
signal toggle_status_screen()
signal damage_dealt(amount: int, source: String)
signal damage_taken(amount: int)
signal chest_opened()
signal save_point_used()
signal game_completed(class_id: String)
signal milestone_updated(key: String, value: int)
signal class_unlocked(class_id: String, unlock_name: String)
signal respec_screen_requested
signal loot_screen_open(drops: Array, source_label: String)
signal loot_screen_closed(remaining: Array)
signal faction_rep_changed(faction_id: String, old_val: int, new_val: int)
signal faction_state_changed(faction_id: String, old_state: String, new_state: String)
signal faction_supporter_gained(faction_id: String)
signal faction_supporter_lost(faction_id: String)
signal faction_joined(faction_id: String)
signal faction_left(faction_id: String)
signal faction_world_action_completed(action: String, details: Dictionary)
signal tax_collected(faction_id: String, amount: int)
signal tax_warning(faction_id: String)
signal tax_expelled(faction_id: String)
signal toggle_faction_screen()

# Crime system (Fase 12)
signal crime_committed(city_id: String)
signal player_arrested(city_id: String, fine_amount: int)
signal crime_cleared(city_id: String)
